In [6]:
import random 
import os

import torch as th 
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [70]:
seed = 546
random.seed(seed)
np.random.seed(seed)
th.manual_seed(seed)
os.environ['PYTHONHASHSEED'] = str(seed)

In [26]:
W = th.tensor([[1., 2.], [3., 4.], [5., 6.], [7., 8.]])
b = th.tensor([0.1, 0.2, 0.3, 0.4])

In [31]:
W 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [147]:
class LinearNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 4)
        self.fc2 = nn.Linear(2, 4)
        self.fc3 = nn.Linear(2, 4)
        with th.no_grad():
          self.fc1.weight.copy_(W)
          self.fc1.bias.copy_(b)
          self.fc2.weight.copy_(2 * W)
          self.fc2.bias.copy_(2 * b)
          self.fc3.weight.copy_(3 * W)
          self.fc3.bias.copy_(3 * b)

    def forward(self, x):
        x = self.fc1(x)
        return x

class ConvNet(nn.Module):
  def __init__(self):
    super().__init__()
    arms = 2
    self.conv1 = nn.Conv1d(in_channels=2 * arms, out_channels=4 * arms, kernel_size=1, groups=arms)

In [150]:
mc = ConvNet()

print(ml.state_dict())
mc.state_dict()

OrderedDict({'fc1.weight': tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]), 'fc1.bias': tensor([0.1000, 0.2000, 0.3000, 0.4000]), 'fc2.weight': tensor([[ 2.,  4.],
        [ 6.,  8.],
        [10., 12.],
        [14., 16.]]), 'fc2.bias': tensor([0.2000, 0.4000, 0.6000, 0.8000]), 'fc3.weight': tensor([[ 3.,  6.],
        [ 9., 12.],
        [15., 18.],
        [21., 24.]]), 'fc3.bias': tensor([0.3000, 0.6000, 0.9000, 1.2000])})


OrderedDict([('conv1.weight',
              tensor([[[-0.4151],
                       [ 0.3930]],
              
                      [[-0.2676],
                       [-0.6095]],
              
                      [[ 0.4881],
                       [ 0.4506]],
              
                      [[-0.6212],
                       [ 0.2400]],
              
                      [[ 0.0949],
                       [-0.3826]],
              
                      [[ 0.1136],
                       [ 0.0898]],
              
                      [[-0.4709],
                       [ 0.1905]],
              
                      [[ 0.2192],
                       [-0.3311]]])),
             ('conv1.bias',
              tensor([-0.2992, -0.1274,  0.3168, -0.3119, -0.1002,  0.2047,  0.6358,  0.3593]))])

In [37]:
ml = LinearNet()

In [43]:
ml.state_dict()['fc1.weight'].shape

torch.Size([4, 2])